apiVersion: apps/v1
kind: Deployment
metadata:
  name: seldon-controller-manager
  namespace: seldon-system
  labels:
    control-plane: seldon-controller-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: seldon-controller-manager
  template:
    metadata:
      labels:
        control-plane: seldon-controller-manager
    spec:
      containers:
      - name: manager
        image: seldonio/seldon-core-operator:1.7.0
        args:
        - --enable-leader-election
        - --webhook.port=9876
        - --operator.metrics-port=8080